[package]
name = "s3-connector"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
rusoto_core = "0.48.0"
rusoto_credential = "0.48.0"
rusoto_s3 = "0.48.0"
tokio = { version = "1.39.3", features = ["full"] }
